title: Lena Armstrong 
logo: "/images/Lena_Armstrong.png"
links: >
  <br>
  <a href = "mailto: lena318@sas.upenn.edu">Email</a> | <a href="https://drive.google.com/file/d/1d2XTwzvVkB-YB3jo1jNnXUShs6lQQ2Xr/view?usp=sharing">CV</a> | <a href="https://www.linkedin.com/in/lena-armstrong/">LinkedIn</a> 
  <br>
description: >
  Lena Armstrong is a recent University of Pennsylvania graduate where she studied computer science and cognitive science. 
  In fall 2024, she start a PhD in Computer Science at Harvard University and work with 
  <a href="http://www.fernandaviegas.com/about">Fernanda Viegas</a> and <a href="https://www.bewitched.com/">Martin Wattenberg</a>
  at the Insight & Interaction Lab.  
  <br><br>
  Her research has focused on human computer interaction, algorithmic fairness, and improving computer science education.
  She is interested in bridging humans and technology for social impact, understanding bias and opacity in automated systems, 
  and encouraging more inclusive experiences in computer science. 


  
theme: jekyll-theme-minimal
google_analytics: G-E0H375SY4D # your Google Analytics tracking ID here
