title: Lena Armstrong 
logo: "/images/Lena_Armstrong.png"
links: >
  <br>
  <a href = "mailto: lena318@sas.upenn.edu">Email</a> | <a href="https://drive.google.com/file/d/1SlgwNE-LnI2-CjbaTGid3TMFwXT9hDvI/view?usp=sharing">CV</a> | <a href="https://www.linkedin.com/in/lena-armstrong/">LinkedIn</a> 
  <br>
description: >
  Lena Armstrong is a computer science and cognitive science double major at the University of Pennsylvania.
  Her research has focused on human computer interaction, algoirthmic fairness, and improving computer science education. 
  She is interested in bridging humans and technology for social impact, creating more fair and transparent automated systems, 
  and encouraging more inclusive and meaningful experiences in computer science. 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
