title: Lena Armstrong
logo: "/images/Lena_Armstrong.png"
description: >
  <br>
  <img src="/images/email_icon.png"
     alt="email icon"
     style="float: left; margin-right: 10px;" />
  <a href = "mailto: lena318@sas.upenn.edu">Email</a> 
  <br>
  <a href="https://drive.google.com/file/d/1SlgwNE-LnI2-CjbaTGid3TMFwXT9hDvI/view?usp=sharing">CV</a> 
  <br>
  <a href="https://www.linkedin.com/in/lena-armstrong/">LinkedIn</a> 
  <br><br>
  Lena is a computer science and cognitive science double major at the University of Pennsylvania. 
  She is interested in mitigating algorithmic bias and improving CS education to create more inclusive and meaningful experiences with technology.
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
