title: Lena Armstrong
logo: "/images/lena-armstrong.png"
links: >
  <br>
  <a href = "mailto: larmstrong@g.harvard.edu">Email</a> 
  <br>
  <a href="https://www.linkedin.com/in/lena-armstrong/">LinkedIn</a>
  <br>
  <a href="https://scholar.google.com/citations?user=ozOmcJQAAAAJ&hl=en&oi=ao">Google Scholar</a>  
  <br>
  <a href="CV.pdf">CV</a>
  <br>
description: >
  
theme: jekyll-theme-minimal
google_analytics: G-E0H375SY4D # your Google Analytics tracking ID here
