title: 
logo: "/images/lena-armstrong.png"
links: >
  <br>
  <a href = "mailto: larmstrong@g.harvard.edu"><img src="/images/email-icon.svg" style="width: 7%; margin-right: 5%"></a> 
  <a href="https://www.linkedin.com/in/lena-armstrong/"><img src="/images/linkedin-icon.svg" style="width: 7%; margin-right: 5%"></a>
  <a href="https://scholar.google.com/citations?user=ozOmcJQAAAAJ&hl=en&oi=ao"><img src="images/scholar-icon.svg" style="width: 7%"></a>  
  <br>
description: >
  
theme: jekyll-theme-minimal
google_analytics: G-E0H375SY4D # your Google Analytics tracking ID here
