title: Lena Armstrong 
logo: "/images/lena-armstrong.png"
links: >
  <br>
  <a href = "mailto: larmstrong@g.harvard.edu"><img src="/images/email-icon.png" style="width: 10%"></a> 
  <a href="https://www.linkedin.com/in/lena-armstrong/"><img src="/images/in.png" style="width: 10%"></a>
  <a href="https://scholar.google.com/citations?user=ozOmcJQAAAAJ&hl=en&oi=ao"><img src="/images/Google_Scholar.png" style="width: 10%"></a>  
  <br>
description: >
  Lena Armstrong is a <a href="https://www.nsfgrfp.org/">NSF Graduate Research Fellow</a> and Computer Science PhD Student at Harvard University, working with 
  <a href="http://www.fernandaviegas.com/about">Fernanda Viegas</a> and <a href="https://www.bewitched.com/">Martin Wattenberg</a>
  at the <a href="https://insight.seas.harvard.edu/">Insight & Interaction Lab</a>.  
  <br><br>
  Her research has focused on human computer interaction, algorithmic justice, and AI auditing.
  She is interested in bridging humans and technology for social impact, understanding bias and opacity in automated systems, 
  and encouraging more inclusive experiences in computer science. 


  
theme: jekyll-theme-minimal
google_analytics: G-E0H375SY4D # your Google Analytics tracking ID here
